### ISSUE TITLE
What the problem here?

### ISSUE THREAD

**Issue by VladChernenko** [JairusSW/as-json#25]
### Hello, help me, please

I have no clue whats going on here and where's mistake. Googling issue also have no results.

So, I have <code>assemblyscript@0.20.19</code> and <code>json-as@0.2.6</code>. Next, I use the <a href="https://github.com/JairusSW/as-json#usage">example</a> from README and the following command to get .wasm module

```shell
asc test.ts -o test.wasm --exportDefault --transform ./node_modules/json-as/transform
```

The failed output stack trace is

```typescript
FAILURE TypeError: Cannot redefine property: signbit
    at Function.defineProperties (<anonymous>)
    at call (webpack://assemblyscript/std/portable/index.js:350:8)
    at null.i (webpack://assemblyscript/webpack/bootstrap:19:32)
    at call (webpack://assemblyscript/src/glue/js/index.ts:6:1)
    at __webpack_require__ (webpack://assemblyscript/webpack/bootstrap:19:32)
    at __webpack_require__ (webpack://assemblyscript/webpack/startup:3:1)
    at factory (webpack://assemblyscript/webpack/startup:5:47)
    at null.<anonymous> (webpack://assemblyscript/webpack/universalModuleDefinition:3:20)
    at Object.<anonymous> (webpack://assemblyscript/webpack/universalModuleDefinition:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)

```

I've try to find docs & common problems, but no results

**Comment by MaxGraey** [comment]
It looks like `portable/index.js` included twice. Similar issue with perhaps useful comment:
https://github.com/AssemblyScript/assemblyscript/issues/1695#issuecomment-801113214

**Comment by MaxGraey** [comment]
It might be enough to clean the npm cache

**Comment by VladChernenko** [comment]
Thanks for quick response, just noticed!👋 Solved the problem in a different way
