### ISSUE TITLE
Support for class inheritance?

### ISSUE THREAD

**Issue by dselman** [JairusSW/as-json#34]
When testing with this file it looks like the value of `person.age` is zero. Is this a bug, or missing feature?

```
// The entry file of your WebAssembly module.

import { JSON } from "json-as/assembly";

// @ts-ignore
@json
class Aged {
  age: i32;
}

// @ts-ignore
@json
class Player extends Aged {
  // age: i32;
  firstName: string;
  lastName: string;
}

// const stringified = JSON.stringify<Player>(data);

export function add(json: string, b: i32): i32 {
  const person = JSON.parse<Player>(json);
  return person.age + b + person.firstName.length;
}
```

**Comment by JairusSW** [comment]
This is a missing feature due to it not being implemented in the transform. Parent type data needs to be cast to the Child data and reflected in the child methods. 
I'll put this on my todo list.
Thank  you for bringing this up!

**Comment by mariusa** [comment]
Hi @JairusSW , the example you posted doesn't work:
```
FAILURE TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable (cannot read property undefined)
    at AsJSONTransform.visitClassDeclaration (node_modules/json-as/transform/lib/index.js:71:47)
```
Thanks!

**Comment by JairusSW** [comment]
It works for me, but it looks like I didn't have an undefined check there.

**Comment by JairusSW** [comment]
@mariusa, can you send me some example code?

**Comment by mariusa** [comment]
Hi, it's exactly the code you posted above:

```
import { wasi_console } from "@assemblyscript/wasi-shim/assembly/wasi_console"
import { u128 } from "as-bignum/assembly"
import {
    JSON
} from "json-as/assembly"

// @ts-ignore
@json
class Vec3 {
    x: f32 = 3.4;
    y: f32 = 1.2;
    z: f32 = 8.3;
}

// @ts-ignore
@json
class Stats extends Vec3 {
    wins: u128
    loss: u128
}

// @ts-ignore
@json
class Player {
    firstName: string
    lastName: string
    lastActive: i32[]
    age: i32
    isVerified: boolean
    stats: Stats
}

const player: Player = {
    firstName: "Emmet",
    lastName: "West",
    lastActive: [8, 27, 2022],
    age: 23,
    isVerified: true,
    stats: {
        wins: u128.fromString("443"),
        loss: u128.fromString("693")
    }
}

const serializedPlayer = JSON.stringify<Player>(player)
wasi_console.log("Serialized Player: " + serializedPlayer)
const deserializedPlayer = JSON.parse<Player>(serializedPlayer)
wasi_console.log("Deserialized Player: " + JSON.stringify(deserializedPlayer))
```

gives
```
FAILURE TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable (cannot read property undefined)
    at AsJSONTransform.visitClassDeclaration (file:///my-project/node_modules/json-as/transform/lib/index.js:71:47)
    at AsJSONTransform._visit (/my-project/node_modules/visitor-as/src/base.ts:269:14)
    at AsJSONTransform._visit (/my-project/node_modules/visitor-as/src/path.ts:13:11)
    at AsJSONTransform.visit (/my-project/node_modules/visitor-as/src/visitor.ts:34:12)
    at TopLevelDecorator.visitDecoratorNode (/my-project/node_modules/visitor-as/src/decorator.ts:39:20)
    at TopLevelDecorator._visit (/my-project/node_modules/visitor-as/src/base.ts:316:14)
    at TopLevelDecorator._visit (/my-project/node_modules/visitor-as/src/path.ts:13:11)
    at TopLevelDecorator.visit (/my-project/node_modules/visitor-as/src/visitor.ts:34:12)
    at <anonymous> (/my-project/node_modules/visitor-as/src/visitor.ts:21:31)
    at Array.map (<anonymous>)
```

**Comment by mariusa** [comment]
This error is solved in current versions
