### ISSUE TITLE
Support for Date

### ISSUE THREAD

**Issue by dselman** [JairusSW/as-json#35]
```
// @ts-ignore
@json
class Player /*extends Aged*/ {
  age: i32;
  firstName: string;
  lastName: string;
  dob: Date;
  // middleName:? string;
}
```

Gives the error:

```
> node tests

file:///Users/dan.selman/dev/cicero-asc/build/debug.js:12
          throw Error(`${message} in ${fileName}:${lineNumber}:${columnNumber}`);
                ^

Error: Could not deserialize data 2022-11-29T12:32:55.631Z to type Date. Invalide data provided. in ~lib/json-as/assembly/src/json.ts:152:13
    at file:///Users/dan.selman/dev/cicero-asc/build/debug.js:12:17
    at abort (file:///Users/dan.selman/dev/cicero-asc/build/debug.js:13:11)
    at ~lib/json-as/assembly/src/json/JSON.parseObjectValue<~lib/date/Date> (wasm://wasm/00015036:wasm-function[90]:0x1c11)
    at assembly/index/Player#__JSON_Set_Key (wasm://wasm/00015036:wasm-function[91]:0x2106)
    at ~lib/json-as/assembly/src/json/JSON.parse<assembly/index/Player> (wasm://wasm/00015036:wasm-function[92]:0x237a)
    at assembly/index/add (wasm://wasm/00015036:wasm-function[93]:0x260d)
    at export:assembly/index/add (wasm://wasm/00015036:wasm-function[98]:0x2bef)
    at add (file:///Users/dan.selman/dev/cicero-asc/build/debug.js:23:22)
    at file:///Users/dan.selman/dev/cicero-asc/tests/index.js:10:20
```

**Comment by JairusSW** [comment]
AssemblyScript doesn't have a fully-supported `Date` API at the moment. Should still be able to support it, its just not fully compat with the JS `Date` API

**Comment by JairusSW** [comment]
I'll do some tinkering with the other date libs

**Comment by JairusSW** [comment]
Starting `Date` implementation in the latest GitHub branch. Should serialize `Date`.
I'll plan to add the ability to parse `Date` later

**Comment by JairusSW** [comment]
So the main issue here is that WebAssembly does not have access to any sort of timing, so it cannot access things like `Date.now()` without bindings to a host function or a runtime that implements WASI.

**Comment by JairusSW** [comment]
Done.

**Comment by JairusSW** [comment]
https://github.com/JairusSW/as-json/commit/2c07ef2dd8eeee1bf4a3d95c2316a6d9709bd2db
Incompat with WASI fixed here
